//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        FlowersEntities1 db = new FlowersEntities1();
        public UserInfo()
        {
            this.Cart = new HashSet<Cart>();
            this.Comment = new HashSet<Comment>();
            this.Order = new HashSet<Order>();
        }

        [Key]
        public int UserID { get; set; }

        [Required]
        [StringLength(20)]
        public string UserName { get; set; }

        [Required(ErrorMessage = "密码不能为空!")]
        [StringLength(16, MinimumLength = 6, ErrorMessage = "密码必须是6-16个字符!")]
        [DataType(DataType.Password)]
        public string UserPwd { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("UserPwd", ErrorMessage = "两次密码不一致!")]
        public string ComfirmPwd { get; set; }

        [Required]
        public string UserPhone { get; set; }
        public string UeserImg { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }


        public void EditUser(UserInfo user)
        {
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
